name="Jawn"
model="gpt-3.5-turbo"
instruction_file="instruction.md"

[[file_bundles]]
bundle_name="source-code"
src_dir="../src/"
src_globs=["**/*.rs"]
dst_ext="rs"

[[file_bundles]]
bundle_name="kowledge"
src_dir="files"
src_globs=["*.md"]
dst_ext="md"
